<a href="https://colab.research.google.com/github/phantom-pixel0/pixel-fatimah/blob/main/stu_assignment_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#TASK 01

marks = np.array([10, 20, 30, 40, 50, 60])

print("Sum:", np.sum(marks))
print("Average:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))

Sum: 210
Average: 35.0
Maximum: 60
Minimum: 10


In [ ]:
import numpy as np
#TASK 2

marks = np.array([45, 80, 30, 90, 55, 20, 88, 77, 55, 35, 90, 100])

print(marks[marks >= 50])


[ 80  90  55  88  77  55  90 100]


In [ ]:
import numpy as np
#TASK 3

marks = np.array([1, 2, 3, 4, 5, 6, 12, 13, 14])

new_marks = marks.reshape(3, 3)

print(new_marks)

[[ 1  2  3]
 [ 4  5  6]
 [12 13 14]]


In [ ]:
import numpy as np
#TASK 4
marks = np.random.randint(40, 101, 12)

print("Marks:", marks)
print("Average:", np.mean(marks))
print("Highest marks:", np.max(marks))
print("Lowest marks:", np.min(marks))

Marks: [52 93 61 82 60 84 58 42 96 71 66 83]
Average: 70.66666666666667
Highest marks: 96
Lowest marks: 42


In [ ]:
import numpy as np
#TASK 5

marks = np.array([30, 67, 44, 45, 90, 25, 70, 95, 50, 55, 66, 99])

passed = marks[marks >= 50]
failed = marks[marks < 50]
topper = marks[marks > 90]

print("Passed marks:", passed)
print("Failed marks:", failed)
print("Topper marks:", topper)
print("-----------------------------")
print("Number of topper students:", len(topper))
print("Number of passed students:", len(passed))
print("Number of failed students:", len(failed))



Passed marks: [67 90 70 95 50 55 66 99]
Failed marks: [30 44 45 25]
Topper marks: [95 99]
-----------------------------
Number of topper students: 2
Number of passed students: 8
Number of failed students: 4


# New Section